import "styles/globals.css";
import { inter } from "app/fonts";
import Head from "next/head";
import { Toaster } from "./components/ui/toaster";
import { ClientProvider } from "utils/trpc-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>
          <link href="logo.svg" />
        </title>
      </Head>
      <body className={inter.className}>
        <ClientProvider>
          <main>{children}</main>
          <Toaster />
        </ClientProvider>
      </body>
    </html>
  );
}
